### ISSUE TITLE
Setting auto_created causes makemigrations issues

### ISSUE THREAD

**Issue by bochecha** [theatlantic/django-select2-forms#22]
The code currently [sets `meta.auto_created` for the `SortableThroughModelBase` class](https://github.com/theatlantic/django-select2-forms/blob/master/select2/models/base.py#L70).

Unfortunately, this means that in our app, when we have a model inheriting from `SortableThroughModel`, then Django's `makemigrations` will ignore that model, and we won't get the tables automatically created.

Worse, if we manually create the migration for this model, then a future `makemigrations` will try to delete it.

Unless we missed something, this means we completely lose the benefits of `makemigrations`, and if we start using `SortableThroughModelBase` then we can't rely on `makemigrations` any more.

Why is `auto_created` set this way? Is there any way to not have it set, so that `makemigrations` works?

Or should we be doing things differently?

**Comment by fdintino** [comment]
I've fixed this in the latest version (2.0.0) by using [django-sortedm2m](https://github.com/gregmuellegger/django-sortedm2m) for this functionality.
