### ISSUE TITLE
how to show "add button" if no results found?

### ISSUE THREAD

**Issue by Megido6** [theatlantic/django-select2-forms#29]
subject

**Comment by Megido6** [comment]
i found  in source params and set to js_options
`'formatNoMatches': 'function () { return "ss"; }'`
in console i see error `Uncaught Error: formatNoMatches must be a function or a falsy value`
which format of formatNoMatches value must be?

**Comment by Megido6** [comment]
i put function get_not_found_block(){} to page head
and try set
'formatNoMatches': 'get_not_found_block()'
or
'formatNoMatches': 'get_not_found_block'

stay same error

**Comment by Megido6** [comment]
up

**Comment by fdintino** [comment]
It is not possible to have javascript code in the select2 options passed in via django. If you need this functionality your best bet is to add your own script that overrides `$.fn.select2.defaults`
