### ISSUE TITLE
ImportError: cannot import name 'force_unicode'

### ISSUE THREAD

**Issue by ArtemBernatskyy** [theatlantic/django-select2-forms#32]
Django 1.9.7, Python 3.4, Ubuntu (Vagrant)

[error](http://pastebin.com/raw/2VbwhvHh)

**Comment by tuomas2** [comment]
Try using one of py3 forks like this: https://github.com/tuomas2/django-select2-forms

**Comment by jonesnc** [comment]
Be sure to use the `py3` branch. https://github.com/tuomas2/django-select2-forms/tree/py3

**Comment by fdintino** [comment]
This is fixed in version 2.0.0.
