### ISSUE TITLE
Version 2.1.0 on pypi?

### ISSUE THREAD

**Issue by lakinwecker** [theatlantic/django-select2-forms#39]
One of the projects that I'm working on is running into an issue with the unicode calls in views.py. These were fixed 3 months ago on master and the 2.1.0 release seems to contain these fixes.

However, pypi only has version 2.0.2 listed so I can't install 2.1.0 with pip. Is there a timeline for when 2.1.0 will be pushed to pypi?

**Comment by fdintino** [comment]
I've uploaded the 2.1.0 release to pypi.
