### ISSUE TITLE
Document that form.media should be put in the templates.

### ISSUE THREAD

**Issue by CharString** [theatlantic/django-select2-forms#4]
I like how you don't render `<script>` in the widget (which is what django-select2 does) as it enables me to put all javascript at the end of the document, using {{form.media.js}} and css in the head using {{form.media.css}}

This should be documented somewhere.

**Comment by fdintino** [comment]
Since this is a Django feature, I think the proper place for this documentation would be in the django docs. It is alluded to in the [documentation on Form.Media](https://docs.djangoproject.com/en/1.10/topics/forms/media/#media-objects) but it is not made explicit in relation to templates.
