### ISSUE TITLE
Make 'Hold down "Control", or "Command" on a Mac, to select more than one.'  hideable.

### ISSUE THREAD

**Issue by CharString** [theatlantic/django-select2-forms#6]
The MultipleSelect still shows 

> Hold down "Control", or "Command" on a Mac, to select more than one.

help_text. It doesn't hurt holding down Control, but it isn't really needed if Select2 kicks in.

I use modernizr, so putting the "Hold down Control" message in a span with a class of "controlmsg" would be great. Then I can hide it with

```
.js .controlmsg {
    display: none;
}
```

and still have it gracefully there when javascript is disabled.

Any better idea for the controlmsg classname? Or another solution for the issue? Perhaps `<noscript>` tags are still allowed?

**Comment by fdintino** [comment]
This ticket is extremely old. But I don't think it applies any longer. I don't see this help text anymore.
